### ISSUE TITLE
throws rethrows 이해하기

### ISSUE THREAD

**Issue by godpp** [boostcamp3-iOS/team-a1#37]
이해하고 Network Layer의 APICenter와 APIManager를 바꿔보자

**Comment by kim-howard** [comment]
👍좋은 스터디 주제인 것 같습니다! 같이 공부해봐요! 
참고로 collection.first 에서도 throw rethrows를 사용하고 있었습니다. 
https://developer.apple.com/documentation/swift/array/1848165-first
